env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'prettier' # Prevent Prettier conflicts
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars:
    - error
globals:
  hljs: true
  imagesLoaded: true
  Isotope: true
  L: true # Global from maps library
  GMaps: true
  Fuse: true
  instantsearch: true
  PagefindUI: readonly
